
// Mock Leads
export const mockLeads = [
    {
        id: "lead1",
        name: "John Smith",
        company: "Acme Inc",
        email: "john@acme.com",
        phone: "(555) 123-4567",
        stage: "New",
        createdAt: "2023-05-15T10:30:00Z",
    },
    {
        id: "lead2",
        name: "Sarah Johnson",
        company: "XYZ Corp",
        email: "sarah@xyz.com",
        phone: "(555) 234-5678",
        stage: "Contacted",
        createdAt: "2023-05-10T14:45:00Z",
    },
    {
        id: "lead3",
        name: "Michael Brown",
        company: "Global Solutions",
        email: "michael@globalsolutions.com",
        phone: "(555) 345-6789",
        stage: "Proposal Sent",
        createdAt: "2023-05-05T09:15:00Z",
    },
    {
        id: "lead4",
        name: "Emily Davis",
        company: "Tech Innovations",
        email: "emily@techinnovations.com",
        phone: "(555) 456-7890",
        stage: "Negotiation",
        createdAt: "2023-04-28T16:20:00Z",
    },
    {
        id: "lead5",
        name: "David Wilson",
        company: "Future Systems",
        email: "david@futuresystems.com",
        phone: "(555) 567-8901",
        stage: "Won",
        createdAt: "2023-04-20T11:10:00Z",
    },
    {
        id: "lead6",
        name: "Jennifer Lee",
        company: "Creative Designs",
        email: "jennifer@creativedesigns.com",
        phone: "(555) 678-9012",
        stage: "Lost",
        createdAt: "2023-04-15T13:25:00Z",
    },
    {
        id: "lead7",
        name: "Robert Taylor",
        company: "Innovative Tech",
        email: "robert@innovativetech.com",
        phone: "(555) 789-0123",
        stage: "New",
        createdAt: "2023-05-18T08:50:00Z",
    },
    {
        id: "lead8",
        name: "Lisa Anderson",
        company: "Smart Solutions",
        email: "lisa@smartsolutions.com",
        phone: "(555) 890-1234",
        stage: "Contacted",
        createdAt: "2023-05-12T15:40:00Z",
    },
]

// Mock Clients
export const mockClients = [
    {
        id: "client1",
        name: "Acme Corporation",
        company: "Acme Corp",
        email: "contact@acmecorp.com",
        phone: "(555) 123-4567",
        status: "Active",
        website: "https://acmecorp.com",
        address: "123 Main St, Suite 100\nNew York, NY 10001",
        notes: "Long-term client since 2018. Prefers communication via email.",
    },
    {
        id: "client2",
        name: "TechStar Solutions",
        company: "TechStar",
        email: "info@techstar.com",
        phone: "(555) 234-5678",
        status: "Active",
        website: "https://techstar.com",
        address: "456 Innovation Way\nSan Francisco, CA 94107",
        notes: "Fast-growing startup. Requires quick response times.",
    },
    {
        id: "client3",
        name: "Global Enterprises",
        company: "Global Ent",
        email: "contact@globalent.com",
        phone: "(555) 345-6789",
        status: "Inactive",
        website: "https://globalent.com",
        address: "789 Corporate Blvd\nChicago, IL 60601",
        notes: "International client with offices in multiple countries.",
    },
    {
        id: "client4",
        name: "Innovative Designs",
        company: "InnoDesign",
        email: "hello@innodesign.com",
        phone: "(555) 456-7890",
        status: "Active",
        website: "https://innodesign.com",
        address: "321 Creative Ave\nAustin, TX 78701",
        notes: "Design-focused client. Appreciates attention to detail.",
    },
    {
        id: "client5",
        name: "Future Systems",
        company: "FutureSys",
        email: "info@futuresys.com",
        phone: "(555) 567-8901",
        status: "New",
        website: "https://futuresys.com",
        address: "555 Technology Park\nBoston, MA 02110",
        notes: "New client onboarded last month. High growth potential.",
    },
    {
        id: "client6",
        name: "Bright Solutions",
        company: "BrightSol",
        email: "contact@brightsol.com",
        phone: "(555) 678-9012",
        status: "Active",
        website: "https://brightsol.com",
        address: "888 Sunshine Blvd\nMiami, FL 33101",
        notes: "Seasonal business with peak demands in summer.",
    },
]

// Mock Projects
export const mockProjects = [
    {
        id: "project1",
        name: "Website Redesign",
        clientId: "client1",
        description: "Complete overhaul of corporate website with new branding and improved user experience.",
        status: "In Progress",
        deadline: "2023-08-15T00:00:00Z",
        budget: 25000,
        totalHours: 120,
        createdAt: "2023-04-10T09:00:00Z",
    },
    {
        id: "project2",
        name: "Mobile App Development",
        clientId: "client1",
        description: "Development of iOS and Android mobile applications for customer engagement.",
        status: "Not Started",
        deadline: "2023-10-30T00:00:00Z",
        budget: 45000,
        totalHours: 0,
        createdAt: "2023-05-05T14:30:00Z",
    },
    {
        id: "project3",
        name: "E-commerce Platform",
        clientId: "client2",
        description: "Implementation of a scalable e-commerce solution with payment processing and inventory management.",
        status: "In Progress",
        deadline: "2023-07-20T00:00:00Z",
        budget: 35000,
        totalHours: 85,
        createdAt: "2023-03-15T11:45:00Z",
    },
    {
        id: "project4",
        name: "Brand Identity",
        clientId: "client4",
        description: "Development of comprehensive brand identity including logo, color palette, and style guide.",
        status: "Completed",
        deadline: "2023-04-30T00:00:00Z",
        budget: 15000,
        totalHours: 60,
        createdAt: "2023-02-20T10:15:00Z",
    },
    {
        id: "project5",
        name: "CRM Implementation",
        clientId: "client3",
        description: "Deployment and customization of CRM system with data migration and user training.",
        status: "On Hold",
        deadline: "2023-09-10T00:00:00Z",
        budget: 30000,
        totalHours: 40,
        createdAt: "2023-04-25T13:20:00Z",
    },
    {
        id: "project6",
        name: "Digital Marketing Campaign",
        clientId: "client5",
        description: "Comprehensive digital marketing campaign across multiple channels to increase brand awareness.",
        status: "In Progress",
        deadline: "2023-08-05T00:00:00Z",
        budget: 20000,
        totalHours: 35,
        createdAt: "2023-05-10T09:30:00Z",
    },
    {
        id: "project7",
        name: "IT Infrastructure Upgrade",
        clientId: "client6",
        description: "Modernization of IT infrastructure including cloud migration and security enhancements.",
        status: "Not Started",
        deadline: "2023-11-15T00:00:00Z",
        budget: 50000,
        totalHours: 0,
        createdAt: "2023-05-18T15:45:00Z",
    },
]

// Mock Tasks
export const mockTasks = [
    {
        id: "task1",
        projectId: "project1",
        title: "Wireframe Design",
        description: "Create wireframes for all main pages of the website.",
        status: "Completed",
        priority: "High",
        createdAt: "2023-04-12T10:30:00Z",
    },
    {
        id: "task2",
        projectId: "project1",
        title: "Frontend Development",
        description: "Implement responsive frontend based on approved designs.",
        status: "In Progress",
        priority: "High",
        createdAt: "2023-04-20T14:15:00Z",
    },
    {
        id: "task3",
        projectId: "project1",
        title: "Backend Integration",
        description: "Connect frontend to backend APIs and implement data flow.",
        status: "To Do",
        priority: "Medium",
        createdAt: "2023-04-25T09:45:00Z",
    },
    {
        id: "task4",
        projectId: "project1",
        title: "Content Migration",
        description: "Migrate existing content to the new website structure.",
        status: "To Do",
        priority: "Low",
        createdAt: "2023-05-01T11:20:00Z",
    },
    {
        id: "task5",
        projectId: "project3",
        title: "Product Catalog Setup",
        description: "Configure product categories, attributes, and import initial inventory.",
        status: "Completed",
        priority: "High",
        createdAt: "2023-03-18T13:10:00Z",
    },
    {
        id: "task6",
        projectId: "project3",
        title: "Payment Gateway Integration",
        description: "Integrate multiple payment gateways and test transaction flow.",
        status: "In Progress",
        priority: "High",
        createdAt: "2023-04-05T10:00:00Z",
    },
    {
        id: "task7",
        projectId: "project3",
        title: "User Authentication System",
        description: "Implement secure user authentication with social login options.",
        status: "Completed",
        priority: "Medium",
        createdAt: "2023-03-25T15:30:00Z",
    },
    {
        id: "task8",
        projectId: "project3",
        title: "Order Management System",
        description: "Develop order processing workflow and notification system.",
        status: "To Do",
        priority: "Medium",
        createdAt: "2023-04-15T09:20:00Z",
    },
]

// Mock Invoices
export const mockInvoices = [
    {
        id: "invoice1",
        clientId: "client1",
        projectId: "project1",
        invoiceNumber: "INV-2023-001",
        date: "2023-04-15T00:00:00Z",
        dueDate: "2023-05-15T00:00:00Z",
        amount: 10000,
        status: "Paid",
        items: [
            {
                id: "item1",
                description: "Website Design - Initial Payment",
                quantity: 1,
                rate: 10000,
                amount: 10000,
            },
        ],
    },
    {
        id: "invoice2",
        clientId: "client1",
        projectId: "project1",
        invoiceNumber: "INV-2023-002",
        date: "2023-05-15T00:00:00Z",
        dueDate: "2023-06-15T00:00:00Z",
        amount: 15000,
        status: "Pending",
        items: [
            {
                id: "item2",
                description: "Website Development - Final Payment",
                quantity: 1,
                rate: 15000,
                amount: 15000,
            },
        ],
    },
    {
        id: "invoice3",
        clientId: "client2",
        projectId: "project3",
        invoiceNumber: "INV-2023-003",
        date: "2023-04-01T00:00:00Z",
        dueDate: "2023-05-01T00:00:00Z",
        amount: 17500,
        status: "Paid",
        items: [
            {
                id: "item3",
                description: "E-commerce Platform - 50% Deposit",
                quantity: 1,
                rate: 17500,
                amount: 17500,
            },
        ],
    },
    {
        id: "invoice4",
        clientId: "client4",
        projectId: "project4",
        invoiceNumber: "INV-2023-004",
        date: "2023-03-10T00:00:00Z",
        dueDate: "2023-04-10T00:00:00Z",
        amount: 15000,
        status: "Paid",
        items: [
            {
                id: "item4",
                description: "Brand Identity Package",
                quantity: 1,
                rate: 15000,
                amount: 15000,
            },
        ],
    },
    {
        id: "invoice5",
        clientId: "client3",
        projectId: "project5",
        invoiceNumber: "INV-2023-005",
        date: "2023-05-05T00:00:00Z",
        dueDate: "2023-06-05T00:00:00Z",
        amount: 12000,
        status: "Pending",
        items: [
            {
                id: "item5",
                description: "CRM Implementation - Initial Phase",
                quantity: 1,
                rate: 12000,
                amount: 12000,
            },
        ],
    },
    {
        id: "invoice6",
        clientId: "client5",
        projectId: "project6",
        invoiceNumber: "INV-2023-006",
        date: "2023-05-12T00:00:00Z",
        dueDate: "2023-06-12T00:00:00Z",
        amount: 8000,
        status: "Pending",
        items: [
            {
                id: "item6",
                description: "Digital Marketing Campaign - Month 1",
                quantity: 1,
                rate: 8000,
                amount: 8000,
            },
        ],
    },
    {
        id: "invoice7",
        clientId: "client2",
        projectId: "project3",
        invoiceNumber: "INV-2023-007",
        date: "2023-03-15T00:00:00Z",
        dueDate: "2023-04-15T00:00:00Z",
        amount: 5000,
        status: "Overdue",
        items: [
            {
                id: "item7",
                description: "Additional Development Services",
                quantity: 50,
                rate: 100,
                amount: 5000,
            },
        ],
    },
]

// Mock Notifications
export const mockNotifications = [
    {
        id: "notification1",
        title: "New lead assigned to you",
        time: "Just now",
        read: false,
    },
    {
        id: "notification2",
        title: "Project 'Website Redesign' deadline approaching",
        time: "2 hours ago",
        read: false,
    },
    {
        id: "notification3",
        title: "Invoice INV-2023-002 is due tomorrow",
        time: "5 hours ago",
        read: false,
    },
    {
        id: "notification4",
        title: "Client meeting scheduled with Acme Corporation",
        time: "Yesterday",
        read: true,
    },
    {
        id: "notification5",
        title: "Task 'Frontend Development' marked as complete",
        time: "2 days ago",
        read: true,
    },
]
